# ===========================================================================
# SMGP FPGA Constraints — Xilinx Alveo U250
# ===========================================================================
# Board: Xilinx Alveo U250 Data Center Accelerator Card
# FPGA:  xcu250-figd2104-2L-e
# ============================================================================

# ---------------------------------------------------------------------------
# System Clock — 250 MHz differential clock (Si570 CML output)
# ---------------------------------------------------------------------------
set_property PACKAGE_PIN F6  [get_ports sys_clk_p]
set_property PACKAGE_PIN E6  [get_ports sys_clk_n]
set_property IOSTANDARD LVDS   [get_ports sys_clk_p]
set_property IOSTANDARD LVDS   [get_ports sys_clk_n]
create_clock -add -name sys_clk_250mhz -period 4.00 -waveform {0 2.00} [get_ports sys_clk_p]

# ---------------------------------------------------------------------------
# Reference Clock for transceivers — 156.25 MHz
# ---------------------------------------------------------------------------
set_property PACKAGE_PIN G6  [get_ports refclk_156_p]
set_property PACKAGE_PIN G5  [get_ports refclk_156_n]
set_property IOSTANDARD LVDS [get_ports refclk_156_p]
set_property IOSTANDARD LVDS [get_ports refclk_156_n]

# ---------------------------------------------------------------------------
# PCIe Gen3 x16 — connection to host CPU
# ---------------------------------------------------------------------------
# PCIe reference clock (100 MHz)
set_property PACKAGE_PIN K3  [get_ports pcie_refclk_p]
set_property PACKAGE_PIN K4  [get_ports pcie_refclk_n]
set_property IOSTANDARD LVDS [get_ports pcie_refclk_p]

# PCIe reset
set_property PACKAGE_PIN L3  [get_ports pcie_perstn]
set_property IOSTANDARD LVCMOS18 [get_ports pcie_perstn]

# PCIe transmit differential pairs (lanes 0-15)
# X0Y0..X0Y3 (Quad 219), X0Y4..X0Y7 (Quad 220), etc.
for {set i 0} {$i < 16} {incr i} {
    set_property IOSTANDARD LVPECL [get_ports pcie_tx_p[$i]]
    set_property IOSTANDARD LVPECL [get_ports pcie_rx_p[$i]]
}

# ---------------------------------------------------------------------------
# HBM (High Bandwidth Memory) — 8 HBM stacks, 2 channels each
# ---------------------------------------------------------------------------
# HBM pseudo-channel clocks are internally generated by the HBM controller.
# These constraints reference the HBM stack locations on the U250.

# HBM Stack 0 (top-left quadrant)
set_property PACKAGE_PIN ... [get_ports hbm_axi_00_0_awaddr]
# NOTE: HBM AXI address/data buses are auto-connected via the Xilinx
#       HBM IP integrator. Pin-level constraints are not user-visible;
#       they are encoded in the HBM hardened macro. The constraints below
#       document the AXI clock relationships.

# HBM AXI clocks — one per pseudo-channel (16 total)
create_clock -add -name hbm_axi_clk_ch00 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_00]
create_clock -add -name hbm_axi_clk_ch01 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_01]
create_clock -add -name hbm_axi_clk_ch02 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_02]
create_clock -add -name hbm_axi_clk_ch03 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_03]
create_clock -add -name hbm_axi_clk_ch04 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_04]
create_clock -add -name hbm_axi_clk_ch05 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_05]
create_clock -add -name hbm_axi_clk_ch06 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_06]
create_clock -add -name hbm_axi_clk_ch07 -period 2.00 [get_pins hbm_controller_0/inst/hbm_axi_clk_07]

# ---------------------------------------------------------------------------
# LEDs — for board-level debug (2 user LEDs near QSFP cage)
# ---------------------------------------------------------------------------
set_property PACKAGE_PIN AJ5 [get_ports user_led[0]]
set_property PACKAGE_PIN AK5 [get_ports user_led[1]]
set_property IOSTANDARD LVCMOS18 [get_ports user_led[0]]
set_property IOSTANDARD LVCMOS18 [get_ports user_led[1]]

# ---------------------------------------------------------------------------
# I2C — for board management controller and QSFP cage monitoring
# ---------------------------------------------------------------------------
set_property PACKAGE_PIN H5 [get_ports i2c_scl]
set_property PACKAGE_PIN J5 [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_scl]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_sda]

# ---------------------------------------------------------------------------
# QSFP28 — 100G Ethernet (optional, for data ingestion)
# ---------------------------------------------------------------------------
# QSFP28 0 (primary)
set_property PACKAGE_PIN D5 [get_ports qsfp0_refclk_p]
set_property PACKAGE_PIN D6 [get_ports qsfp0_refclk_n]
set_property IOSTANDARD LVDS [get_ports qsfp0_refclk_p]

# ---------------------------------------------------------------------------
# Timing constraints
# ---------------------------------------------------------------------------
# Cross-clock domain: PCIe to HBM (async bridge)
set_max_delay -datapath_only -from [get_clocks -include_generated_clocks pcie_refclk] \
               -to [get_clocks -include_generated_clocks hbm_axi_clk_ch00] 15.0

# Internal logic timing
set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks sys_clk_250mhz] \
    -group [get_clocks -include_generated_clocks hbm_axi_clk_ch*] \
    -group [get_clocks -include_generated_clocks pcie_refclk]
